using System.Linq;
using System.Threading;
using NUnit.Framework;

namespace ProjectEuler.Tests
{
    [TestFixture]
    public class FibonacciTests
    {
        [Test]
        public void FibonacciSequenceIsCorrectFOrFirst10()
        {
            // Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
            var expectedArray = new [] {1, 2, 3, 5, 8, 13, 21, 34, 55, 89};
            var actualArray = Fibonacci.GetSequence(10);
            Assert.IsTrue(expectedArray.SequenceEqual(actualArray), "Arrays do not match!");
        }
    }
}